const data = {
    products:[
        {
            name:'Styleville.in Women is A-Line Midi Dress',
            slug:'styleville.in women is a-Line midi dress',
            category:'Dresses',
            image:'/images/p1.jpg',
            price:70,
            brand:'TrendBux®',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Buy Styleville.in Women is A-Line Midi Dress from Dresses at Amazon.in. 30 days free exchange or return',
        },
        {
            name:'Strawberry Midi Dress Black',
            slug:'strawberry midi Dress black',
            category:'Dresses',
            image:'/images/p2.jpg',
            price:70,
            brand:'Lirika Matoshi',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Buy Styleville.in Women is A-Line Midi Dress from Dresses at Amazon.in. 30 days free exchange or return',
        },
        {
            name:'Synthetic A-Line Dress',
            slug:'synthetic a-line dress',
            category:'Dresses',
            image:'/images/p3.jpg',
            price:70,
            brand:'Rare',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'This product is made from polyester and finished in an enticing black color. It features printed pattern, Half Sleeve, V-neck, and is targeted towards girls. Furthermore, it is counseled to be steer clear off extreme heat, fire and corrosive liquids to avoid any type of harm.',
        },
        {
            name:'Floral Print Fit & Flare Dress',
            slug:'floral print fit & flare dress',
            category:'Dresses',
            image:'/images/p4.jpg',
            price:70,
            brand:'Rare',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Buy Styleville.in Women is A-Line Midi Dress from Dresses at Amazon.in. 30 days free exchange or return',
        },
        {
            name:'Printed Full Length Green LIVA Dress',
            slug:'printed full length green liva dress',
            category:'Dresses',
            image:'/images/p5.jpg',
            price:70,
            brand:'More by Honey',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Womens printed casual dress featuring a collared neck, three fourth sleeves, full length and a regular fit. It is crafted from fine Liva. The model (height 5 ft 7 in) is wearing Size M',
        },
        {
            name:'Saingace Women is Black Dresses',
            slug:'saingace women is black dresses',
            category:'Dresses',
            image:'/images/p6.jpeg',
            price:70,
            brand:'Saingace',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Dress for Women Western Women is Halter Neck Spaghetti Straps Summer Dress Sleeveless Sexy Mini Dress Women is O-Neck Boho Sleeveless Summer Beach Sundress Floral Printed Casual T-Shirt Short Mini Dress Women is High Neck Hollow Out Lace Long Sleeve Bodycon Pencil Midi Dress',
        },
    ],
};
export default data;
