const data = {
    products:[
        {
            name:'Styleville.in Women is A-Line Midi Dress',
            slug:'styleville.in women is a-Line midi dress',
            category:'Dresses',
            image:'/images/p1.jpg',
            price:70,
            brand:'TrendBux®',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Buy Styleville.in Women is A-Line Midi Dress from Dresses at Amazon.in. 30 days free exchange or return',
        },
        {
            name:'Styleville.in Women is A-Line Midi Dress',
            slug:'styleville.in women is a-Line midi dress',
            category:'Dresses',
            image:'/images/p2.jpg',
            price:70,
            brand:'TrendBux®',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Buy Styleville.in Women is A-Line Midi Dress from Dresses at Amazon.in. 30 days free exchange or return',
        },
        {
            name:'Synthetic A-Line Dress – Rare',
            slug:'synthetic a-line dress – rare',
            category:'Dresses',
            image:'/images/p3.jpg',
            price:70,
            brand:'TrendBux®',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'This product is made from polyester and finished in an enticing black color. It features printed pattern, Half Sleeve, V-neck, and is targeted towards girls. Furthermore, it is counseled to be steer clear off extreme heat, fire and corrosive liquids to avoid any type of harm.',
        },
        {
            name:'Styleville.in Women is A-Line Midi Dress',
            slug:'styleville.in women is a-Line midi dress',
            category:'Dresses',
            image:'/images/p4.jpg',
            price:70,
            brand:'TrendBux®',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Buy Styleville.in Women is A-Line Midi Dress from Dresses at Amazon.in. 30 days free exchange or return',
        },
        {
            name:'Styleville.in Women is A-Line Midi Dress',
            slug:'styleville.in women is a-Line midi dress',
            category:'Dresses',
            image:'/images/p5.jpg',
            price:70,
            brand:'TrendBux®',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Buy Styleville.in Women is A-Line Midi Dress from Dresses at Amazon.in. 30 days free exchange or return',
        },
        {
            name:'Styleville.in Women is A-Line Midi Dress',
            slug:'styleville.in women is a-Line midi dress',
            category:'Dresses',
            image:'/images/p6.jpeg',
            price:70,
            brand:'TrendBux®',
            rating:4.5,
            numReviews:10,
            countInStock:20,
            description:'Buy Styleville.in Women is A-Line Midi Dress from Dresses at Amazon.in. 30 days free exchange or return',
        },
    ],
};
export default data;
